### ISSUE TITLE
i18n crash

### ISSUE THREAD

**Issue by achingbrain** [workshopper/workshopper#132]
I've recently merged tableflip/nodebot-workshop#29 which adds a Japanese translation to the nodebot-workshop workshopper yet every time I change the language and then choose an exercise workshopper crashes.

I've created a minimal repo that reproduces the issue - [achingbrain/workshopper-i18n-test](https://github.com/achingbrain/workshopper-i18n-test).  Any ideas what's causing the crash?

The stack trace is:

```
events.js:85
      listeners[i].call(self);
                  ^

TypeError: Cannot read property 'call' of undefined
    at emitNone (events.js:85:19)
    at Stream.emit (events.js:179:7)
    at Stream.Charm.end (/Users/alex/Documents/Workspaces/achingbrain/workshopper-test/node_modules/charm/index.js:107:10)
    at Menu.close (/Users/alex/Documents/Workspaces/achingbrain/workshopper-test/node_modules/terminal-menu/index.js:126:16)
    at Menu.<anonymous> (/Users/alex/Documents/Workspaces/achingbrain/workshopper-test/node_modules/workshopper/menu.js:75:10)
    at emitTwo (events.js:105:20)
    at Menu.emit (events.js:185:7)
    at Menu.ondata [as _ondata] (/Users/alex/Documents/Workspaces/achingbrain/workshopper-test/node_modules/terminal-menu/index.js:215:18)
    at DestroyableTransform._transform (/Users/alex/Documents/Workspaces/achingbrain/workshopper-test/node_modules/terminal-menu/index.js:50:18)
    at DestroyableTransform.Transform._read (/Users/alex/Documents/Workspaces/achingbrain/workshopper-test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/alex/Documents/Workspaces/achingbrain/workshopper-test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/alex/Documents/Workspaces/achingbrain/workshopper-test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/alex/Documents/Workspaces/achingbrain/workshopper-test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/alex/Documents/Workspaces/achingbrain/workshopper-test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

I notice the async-you workshopper also has the same problem when changing languages.

**Comment by achingbrain** [comment]
FWIW if I comment out [this line in menu.js](https://github.com/workshopper/workshopper/blob/5a6b9a69818e8b671b06fade4cddb376ade0e971/menu.js#L75) language selection works as expected.

Anyone know why it's necessary to call `menu.close()`?

**Comment by martinheidegger** [comment]
Did you try the same thing in workshopper-adventure?

**Comment by achingbrain** [comment]
I gave workshopper-adventure a go but saw a different crash so figured it wasn't a drop-in replacement.

**Comment by martinheidegger** [comment]
workshopper-adventure should be a 100% drop-in replacement but it could very well be that I screwed up 😛  If you have time I would love to explore your problems on gitter / im.

**Comment by martinheidegger** [comment]
I closed this issue because of lack of progress. Please reopen if you feel that was premature.
